--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ZulfahmiFjr/SoulWell
build-by-default: true
branches:
- stable 
projects:
  SoulWell:
    path: ""
    libs:
      - src: skymin/InventoryLib
        version: ^3.1.1
...
